### PR TITLE
Node js v10 update

### PR DESCRIPTION
**Pull request by thystonius**
**This will need to be merged after the Serial Port Update from @ellisgl **
See [his pull request](https://github.com/LaserWeb/lw.comm-server/pull/67) for update to serial port.

Making this pull request to get some more eyes on the changes to move to Node v10.
Most of the changes are just package updates.  But there is one section of actual code changed in config.js because .env returns string when you actually use a .env file.

Electron builder does build and run, BUT ALSO requires an update to the .travis.yml in LaserWeb4, so I'm making a separate pull request for that.

I've tested running on live machines with grbl & smoothie.

I would REALLY appreciate it if someone else could take a look at this and give me some feedback.

### CODE REVIEW

**Comment by cprezzi** [comment]
@thystonius You are writiing that the pull request of ellisgl needs to be merged first but his pr is for branch electron_bundler, yours is in master.

**Comment by thystonius** [comment]
The electron builder complained about 'electron-rebuild' and it was in a version release note.   I'm re-reading the electron-rebuild docs now to double check as that might need a version bump too.   I'll find out and link the article.

Next, my mistake on ellisgl's branch.  I was trying to keep the two branches separate so I was hand merging his code to test things then I removed it to make the pull request.  Where would you like things to go?

**Comment by cprezzi** [comment]
Up till now all server development was made in master which is also used for separate server installations like on Raspberry Pi. The changes was then merged to electron-builder für compiling the app.

**Comment by thystonius** [comment]
Ok, I'll take another stab at it.

**Comment by thystonius** [comment]
OK, I've gotten a few things sorted out, but can you tell me the steps you
use to build the electron app.  I can build it now, but I want to make sure
I'm doing it just like you are.

**Comment by cprezzi** [comment]
@jorgerobles was always the guy how cared about compiling the electron app.
Lets see if I can remember the process correctly:

1. cd lw.comm-server
2. git pull
3. git checkout electron-bundler
4. git merge master
5. npm run nightlywindows (or nightlylinux)

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4-Binaries has all the necessary to build LW. 😉

**Comment by thystonius** [comment]
Ahh!  Thank You!

**Comment by thystonius** [comment]
Closing - not ready.

**Pull request closed without merging**
